@api = cDZHYzlZa0JadVREZDJCendQbXY6SkJlTzNjLV9TRENyQk1RdnFKZGRQdw==

### GET TJGO
GET https://api-publica.datajud.cnj.jus.br/api_publica_tjgo/_search
Content-Type: application/json
Authorization: APIKey {{api}}

{
    "query": {
        "match": {
            "numeroProcesso": "51790859320228090087"
        }
    }
}

### GET TJMG
GET https://api-publica.datajud.cnj.jus.br/api_publica_tjmg/_search
Content-Type: application/json
Authorization: APIKey {{api}}

{
    "query": {
        "match": {
            "numeroProcesso": "50007094120198130035"
        }
    }
}

### GET TJTO
GET https://api-publica.datajud.cnj.jus.br/api_publica_tjto/_search
Content-Type: application/json
Authorization: APIKey {{api}}

{
    "query": {
        "match": {
            "numeroProcesso": "00007141420258272731"
        }
    }
}

### GET TJMG - Busca por número sem zeros à esquerda
GET https://api-publica.datajud.cnj.jus.br/api_publica_tjmg/_search
Content-Type: application/json
Authorization: APIKey {{api}}

{
    "query": {
        "match": {
            "numeroProcesso": "5000709-41.2019.8.13.0035"
        }
    }
}

### GET TJMG - Busca por partes (polo ativo)
GET https://api-publica.datajud.cnj.jus.br/api_publica_tjmg/_search
Content-Type: application/json
Authorization: APIKey {{api}}

{
    "query": {
        "match": {
            "partes.nome": "Adir Floriano Lemos"
        }
    }
}
