HTTP/1.1 200 OK
Date: Mon, 18 May 2026 12:26:14 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: close
Server: nginx
X-Powered-By: PHP/8.2.26
Cache-Control: no-cache, private
X-RateLimit-Limit: 60
X-RateLimit-Remaining: 59
Access-Control-Allow-Origin: *

{
  "1033": {
    "HEADER": {
      "PARAMETROS": {
        "CPFCNPJ": "81584278000155"
      },
      "DADOS_RETORNADOS": {
        "DADOS_RECEITA_FEDERAL": "0",
        "ALERTA_DOCUMENTOS_ROUBADOS": "0",
        "DADOS_AGENCIA_BANCARIA": "0",
        "PROTESTO_SINTETICO": "1",
        "PROTESTO_ANALITICO": "0",
        "ENDERECOS": "0",
        "FALENCIAS_ACOES_RECUPERACOES": "0",
        "INFORMACOES_ELEITORAIS": "0",
        "QUADRO_SOCIETARIO": "0",
        "PARTICIPACAO_EM_EMPRESAS": "0",
        "PENDENCIAS_INTERNAS": "0",
        "PENDENCIAS_FINANCEIRAS": "0",
        "INFORMACOES_DA_EMPRESA": "0",
        "CCF_BACEN": "0",
        "CCF_VAREJO": "0",
        "RECHEQUE_ONLINE": "0",
        "RECHEQUE": "0",
        "CONTUMACIA": "0",
        "ENDERECO_DO_CEP": "0",
        "PASSAGENS_COMERCIAIS": "0",
        "INFORMACOES_ALERTAS_RESTRICOES": "0",
        "SCORE": "0",
        "ADMINISTRADORES_DA_EMPRESA": "0",
        "TITULOS_A_VENCER": "0",
        "HISTORICO_DE_PAGAMENTOS": "0",
        "REFERENCIA_DE_NEGOCIOS": "0",
        "PRINCIPAIS_FORNECEDORES": "0",
        "IDENTIFICACAO_PESSOA_FISICA": "0",
        "OCUPACAO_PESSOA_FISICA": "0",
        "PARTICIPACAO_EM_FALENCIAS": "0",
        "TELEFONE_FIXO": "0",
        "TITULAR_DO_TELEFONE": "0",
        "OUTROS_TELEFONES": "0",
        "TELEFONE_CELULAR": "0",
        "PARENTES": "0",
        "CONTATOS": "0",
        "LOCAIS_TRABALHO": "0",
        "TELEFONE_COMERCIAL": "0",
        "DADOS_GERAIS": "0",
        "VIZINHOS": "0",
        "RESIDENTES": "0",
        "BENEFICIO": "0",
        "EMAILS": "0",
        "INFOBUSCA": "0",
        "VINCULO_MESMO_ENDERECO": "0",
        "SOMENTE_TELEFONE": "0",
        "SOMENTE_ENDERECO": "0",
        "RELATORIO_TEXTO": "0",
        "VEICULOS_POR_DOCUMENTO": "0",
        "CNH": "0",
        "AGREGADOS": "0",
        "BIN_NACIONAL": "0",
        "BIN_ESTADUAL": "0",
        "GRAVAME": "0",
        "LEILAO": "0",
        "CONFERENCIA_MOTOR_E_CHASSI": "0",
        "HISTORICO_PROPRIETARIOS": "0",
        "HISTORICO_ROUBO_FURTO": "0",
        "ROUBO_FURTO": "0",
        "PERDA_TOTAL": "0",
        "ALERTAS": "0",
        "RECALL": "0",
        "DPVAT": "0",
        "DECODIFICADOR_DE_CHASSI": "0",
        "PRECIFICADOR": "0",
        "RENAJUD": "0",
        "RENACH": "0",
        "CRLV": "0",
        "REMARKETING": "0",
        "INDICIO_SINISTRO": "0",
        "PARECER_TECNICO": "0",
        "PENDENCIAS_REFIN": "0",
        "PENDENCIAS_VENCIDAS": "0",
        "LOCALIZADOR_AGREGADOS": "0",
        "CARACTERISTICAS_ADICIONAIS": "0",
        "LAUDO_CAUTELAR": "0",
        "DECISAO": "0",
        "LIMITE_CREDITO": "0",
        "FATURAMENTO_PRESUMIDO": "0",
        "PARTICIPACAO_SOCIO_ADM_OUTRAS_EMPRESAS": "0",
        "PARTICIPACOES_EMPRESAS_CONSULTADAS": "0",
        "HIST_CONSULTAS": "0",
        "ACOES_CIVEIS": "0",
        "FALENCIA_RECUPERACAO_JUDICIAL": "0",
        "ANALISE_KILOMETRAGEM": "0",
        "PONTUALIDADE_PAGTO": "0",
        "PROPRIETARIO_ATUAL_VEICULO": "0",
        "VALIDACAO_PESSOA_FISICA": "0",
        "VALIDACAO_PF_BASICA": "0",
        "VALIDACAO_PF_BIOMETRIA_FACE": "0",
        "VALIDACAO_PF_CNH": "0",
        "VALIDACAO_PF_DOCUMENTO": "0",
        "VALIDACAO_PF_ENDERECO": "0",
        "VALIDACAO_PF_FILIACAO": "0",
        "AUTO_VISTORIA": "0",
        "INDICE_SECURITARIO": "0",
        "CALCULO_VALORIZACAO": "0",
        "ATPVE": "0",
        "CREDITO_CONCEDIDO": "0",
        "RENDA_PRESUMIDA": "0",
        "COMPROMETIMENTO_PAGTO": "0",
        "LEILAO_CONJUGADO": "0",
        "CSV": "0",
        "RENAINF": "0",
        "RELATORIO_ARQUIVO": "0",
        "INDICIO_SINISTRO_CONJUGADO": "0",
        "CONSULTA_GENERICA": "0",
        "BATIDOS": "0",
        "RELATORIO_SCR": "0",
        "CADIN": "0",
        "ACOES_TRABALHISTAS": "0",
        "RELATORIO_SCR_SINTETICO": "0",
        "CPR": "0",
        "FICHA_TECNICA_VEICULAR": "0",
        "CHECK_LIST_VEICULAR": "0",
        "DIVIDA_ATIVA_PESSOA_FISICA": "0",
        "DIVIDA_ATIVA_PESSOA_JURIDICA": "0",
        "PENDENCIAS_ISP": "0",
        "RELATORIO_JURIDICO_EMPRESARIAL": "0",
        "INFORMACOES_CRIMINAIS": "0",
        "PROCURADOS_JUSTICA": "0",
        "RELATORIO_JURIDICO_PESSOA_FISICA": "0",
        "DETALHAMENTO_ACAO_JUDICIAL": "0",
        "RELATORIO_IMOVEIS": "0",
        "DEBITOS_IPVA": "0",
        "DEBITO_DIRETO_AUTORIZADO": "0",
        "CONTROLE_POSITIVO": "0",
        "ALERTA_INDICIO": "0",
        "RELATORIO_CREDITICIO_ARQUIVO": "0",
        "IMAGENS_VEICULO": "0",
        "RELATORIO_SCR_ENCAPSULADO": "0",
        "RESTRICOES_FINANCEIRAS": "0",
        "ALERTA_VEICULAR_PROPRIEDADE": "0",
        "MOTOR_CREDITO": "0",
        "ALTERACAO_CARACTERISTICAS": "0",
        "DEBITOS_VEICULARES": "0",
        "RESTRICOES_SINTETICAS": "0",
        "ACOES_JUDICIAIS_COMPLETAS": "0",
        "PERIODO_RELACIONAMENTO_FORNECEDORES": "0",
        "EVENTOS_PESSOA_JURIDICA": "0",
        "CREDITO_OBTIDO": "0",
        "COMPROMISSOS": "0",
        "PAGAMENTO_PONTUAL": "0",
        "PAGAMENTO_ATRASADO": "0",
        "COMPROMETIMENTO_FUTURO": "0",
        "ANTECEDENTES_PESSOAIS": "0",
        "COMUNICADO_VENDA": "0",
        "ANTT_TRANSPORTADOR": "0",
        "ANTT_VEICULO": "0",
        "HIST_TRANSFERENCIA_NACIONAL": "0"
      },
      "CONTROLE": {
        "QUANTIDADE_OCORRENCIAS": "1",
        "OCORRENCIAS": [
          {
            "CONTEUDO": "41",
            "FONTE": "117",
            "STATUS": "1"
          }
        ],
        "CACHE_GERAL": []
      },
      "STATUS_RETORNO": {
        "CODIGO": "1",
        "DESCRICAO": "CONSULTA CONCLUIDA COM SUCESSO"
      }
    },
    "CREDCADASTRAL": {
      "PROTESTO_SINTETICO": {
        "STATUS_RETORNO": {
          "CODIGO": "1",
          "DESCRICAO": "CONSULTA CONCLUIDA COM SUCESSO"
        },
        "VALOR_TOTAL": "1293,74",
        "ULTIMO_PROTESTO": "",
        "QUANTIDADE_OCORRENCIA": "2",
        "OCORRENCIAS": [
          {
            "UF": "MS",
            "TELEFONE": "6734731232",
            "ENDERECO": "RUA S\u00c3O PAULO, 1229 CAIXA POSTAL 04 CENTRO",
            "CARTORIO": "ELDORADO - SERVI\u00c7O DE REG. DE IM\u00d3VEIS E PROTESTO",
            "COMARCA": "ELDORADO",
            "INFO_CARTORIOS": "",
            "DATA_OCORRENCIA": "",
            "DATA_ATUALIZACAO": "",
            "VALOR": "586,00",
            "CREDOR": "",
            "CEDENTE": "",
            "ANUENCIA": "NAO POSSUI ANUENCIA",
            "VALOR_CUSTAS": ""
          },
          {
            "UF": "MS",
            "TELEFONE": "6734527134",
            "ENDERECO": "DR. BOAVENTURA, 968 CENTRO, 968 CENTRO",
            "CARTORIO": "TABELIONATO DE PROTESTO DE T\u00edTULOS E OUTROS DOCUMENTOS DE D\u00edVIDA",
            "COMARCA": "RIO BRILHANTE",
            "INFO_CARTORIOS": "",
            "DATA_OCORRENCIA": "",
            "DATA_ATUALIZACAO": "",
            "VALOR": "707,74",
            "CREDOR": "",
            "CEDENTE": "",
            "ANUENCIA": "NAO POSSUI ANUENCIA",
            "VALOR_CUSTAS": ""
          }
        ]
      }
    },
    "VEICULAR": []
  }
}