### SPC - Configuração de Credenciais
# Configure suas credenciais do SPC:
@username = 131244831
@password = Mf19842025*
@cnpj = 04639628000192
@cpf = 06604890660

### IMPORTANTE: Problema com Homologação
# O servidor de homologação (homologacao1.spc.org.br) está inacessível
# Use o endpoint de teste para verificar a conectividade:
# GET /report/spc/test

### SPC - Consulta Padrão (Homologação)
POST https://homologacao1.spc.org.br:443/spcconsulta/recurso/consulta/padrao
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "codigoProduto": "1172",
  "tipoConsumidor": "J",
  "documentoConsumidor": "02178451000149",
  "codigoInsumoOpcional": []
}

### SPC - Consulta Padrão (Produção)
POST https://servicos.spc.org.br/spcconsulta/recurso/consulta/padrao
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "codigoProduto": "325",
  "tipoConsumidor": "J",
  "documentoConsumidor": "04639628000192",
  "codigoInsumoOpcional": [78]
}


### SPC - Consulta com CNPJ diferente
POST https://servicos.spc.org.br/spcconsulta/recurso/consulta/padrao
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "codigoProduto": "325",
  "tipoConsumidor": "J",
  "documentoConsumidor": "{{cnpj}}",
  "codigoInsumoOpcional": [78]
}

### SPC - Consulta Pessoa Física
POST https://servicos.spc.org.br/spcconsulta/recurso/consulta/padrao
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "codigoProduto": "695",
  "tipoConsumidor": "F",
  "documentoConsumidor": "{{cpf}}",
  "codigoInsumoOpcional": []
}
